// item: "2007 Ford Focus Radio",
//             partNo: "1234",
//             sku: "1234",
//             listed: false,
//             location: "",
//             datePurchased: new Date().toDateString(),
//             dateSold: new Date().toDateString(),
//             purchasePrice: 9.99,
//             listedPrice: 0,
//             priceSold: 125.50,
//             shippingCost: 15.74,
//             ebayFees: 10,
//             payPalFees: 10,
//             profit: 200,
//             ebayItemId: "",
//             id: 1111,
//             expectedProfit: 0